=begin
#Paubox Email API

#Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'cgi'

module Paubox
  class MessagesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get email disposition
    # Retrieve delivery status, open tracking, and click tracking information for a sent message
    # @param source_tracking_id [String] The tracking ID returned when the message was sent
    # @param [Hash] opts the optional parameters
    # @return [MessageReceiptResponse]
    def get_message_receipt(source_tracking_id, opts = {})
      data, _status_code, _headers = get_message_receipt_with_http_info(source_tracking_id, opts)
      data
    end

    # Get email disposition
    # Retrieve delivery status, open tracking, and click tracking information for a sent message
    # @param source_tracking_id [String] The tracking ID returned when the message was sent
    # @param [Hash] opts the optional parameters
    # @return [Array<(MessageReceiptResponse, Integer, Hash)>] MessageReceiptResponse data, response status code and response headers
    def get_message_receipt_with_http_info(source_tracking_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MessagesApi.get_message_receipt ...'
      end
      # verify the required parameter 'source_tracking_id' is set
      if @api_client.config.client_side_validation && source_tracking_id.nil?
        fail ArgumentError, "Missing the required parameter 'source_tracking_id' when calling MessagesApi.get_message_receipt"
      end
      # resource path
      local_var_path = '/message_receipt'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'sourceTrackingId'] = source_tracking_id

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MessageReceiptResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PauboxToken']

      new_options = opts.merge(
        :operation => :"MessagesApi.get_message_receipt",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MessagesApi#get_message_receipt\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Send multiple email messages (batch)
    # Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
    # @param bulk_send_request [BulkSendRequest] 
    # @param [Hash] opts the optional parameters
    # @return [BulkSendResponse]
    def send_bulk_messages(bulk_send_request, opts = {})
      data, _status_code, _headers = send_bulk_messages_with_http_info(bulk_send_request, opts)
      data
    end

    # Send multiple email messages (batch)
    # Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
    # @param bulk_send_request [BulkSendRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(BulkSendResponse, Integer, Hash)>] BulkSendResponse data, response status code and response headers
    def send_bulk_messages_with_http_info(bulk_send_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MessagesApi.send_bulk_messages ...'
      end
      # verify the required parameter 'bulk_send_request' is set
      if @api_client.config.client_side_validation && bulk_send_request.nil?
        fail ArgumentError, "Missing the required parameter 'bulk_send_request' when calling MessagesApi.send_bulk_messages"
      end
      # resource path
      local_var_path = '/bulk_messages'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(bulk_send_request)

      # return_type
      return_type = opts[:debug_return_type] || 'BulkSendResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PauboxToken']

      new_options = opts.merge(
        :operation => :"MessagesApi.send_bulk_messages",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MessagesApi#send_bulk_messages\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Send a single email message
    # @param single_send_request [SingleSendRequest] 
    # @param [Hash] opts the optional parameters
    # @return [SingleSendResponse]
    def send_message(single_send_request, opts = {})
      data, _status_code, _headers = send_message_with_http_info(single_send_request, opts)
      data
    end

    # Send a single email message
    # @param single_send_request [SingleSendRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(SingleSendResponse, Integer, Hash)>] SingleSendResponse data, response status code and response headers
    def send_message_with_http_info(single_send_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MessagesApi.send_message ...'
      end
      # verify the required parameter 'single_send_request' is set
      if @api_client.config.client_side_validation && single_send_request.nil?
        fail ArgumentError, "Missing the required parameter 'single_send_request' when calling MessagesApi.send_message"
      end
      # resource path
      local_var_path = '/messages'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(single_send_request)

      # return_type
      return_type = opts[:debug_return_type] || 'SingleSendResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PauboxToken']

      new_options = opts.merge(
        :operation => :"MessagesApi.send_message",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MessagesApi#send_message\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
