=begin
#Paubox Email API

#Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Paubox::DynamicTemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DynamicTemplatesApi' do
  before do
    # run before each test
    @api_instance = Paubox::DynamicTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DynamicTemplatesApi' do
    it 'should create an instance of DynamicTemplatesApi' do
      expect(@api_instance).to be_instance_of(Paubox::DynamicTemplatesApi)
    end
  end

  # unit tests for create_dynamic_template
  # Create a dynamic template
  # Upload a new Handlebars template for dynamic content generation
  # @param data_name Name for the template
  # @param data_body Handlebars template file (.hbs)
  # @param [Hash] opts the optional parameters
  # @return [DynamicTemplateResponse]
  describe 'create_dynamic_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_dynamic_template
  # Delete a dynamic template
  # Delete a specific dynamic template by ID
  # @param id Template ID to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteDynamicTemplate200Response]
  describe 'delete_dynamic_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_dynamic_template
  # Get a dynamic template
  # Retrieve a specific dynamic template by ID
  # @param id Template ID
  # @param [Hash] opts the optional parameters
  # @return [DynamicTemplateResponse]
  describe 'get_dynamic_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_dynamic_templates
  # List all dynamic templates
  # Retrieve all dynamic templates for your organization
  # @param [Hash] opts the optional parameters
  # @return [DynamicTemplateListResponse]
  describe 'list_dynamic_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_templated_message
  # Send a dynamically templated message
  # Send an email using a dynamic template with variable substitution
  # @param templated_message_request 
  # @param [Hash] opts the optional parameters
  # @return [SingleSendResponse]
  describe 'send_templated_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_dynamic_template
  # Update a dynamic template
  # Update an existing Handlebars template
  # @param id Template ID to update
  # @param [Hash] opts the optional parameters
  # @option opts [String] :data_name Updated name for the template
  # @option opts [File] :data_body Updated Handlebars template file (.hbs)
  # @return [DynamicTemplateResponse]
  describe 'update_dynamic_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
