=begin
#Paubox Email API

#Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Paubox::BulkSendRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Paubox::BulkSendRequest do
  #let(:instance) { Paubox::BulkSendRequest.new }

  describe 'test an instance of BulkSendRequest' do
    it 'should create an instance of BulkSendRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Paubox::BulkSendRequest)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
