=begin
#Paubox Email API

#Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Paubox::DeliveryStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Paubox::DeliveryStatus do
  #let(:instance) { Paubox::DeliveryStatus.new }

  describe 'test an instance of DeliveryStatus' do
    it 'should create an instance of DeliveryStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Paubox::DeliveryStatus)
    end
  end

  describe 'test attribute "delivery_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["processing", "TLS not offered, sending via Secure Portal", "soft bounced", "soft bounced - mailbox full", "hard bounced", "Internal error. Please check back later.", "delivered", "delivered via secure portal"])
      # validator.allowable_values.each do |value|
      #   expect { instance.delivery_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "delivery_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "opened_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["opened", "not opened"])
      # validator.allowable_values.each do |value|
      #   expect { instance.opened_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "opened_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
