=begin
#Paubox Email API

#Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

# Common files
require 'paubox/api_client'
require 'paubox/api_error'
require 'paubox/api_model_base'
require 'paubox/version'
require 'paubox/configuration'

# Models
require 'paubox/models/attachment'
require 'paubox/models/bulk_send_request'
require 'paubox/models/bulk_send_request_data'
require 'paubox/models/bulk_send_response'
require 'paubox/models/bulk_send_response_messages_inner'
require 'paubox/models/click_data'
require 'paubox/models/delete_dynamic_template200_response'
require 'paubox/models/delivery_status'
require 'paubox/models/dynamic_template_list_response'
require 'paubox/models/dynamic_template_response'
require 'paubox/models/error_response'
require 'paubox/models/error_response_errors_inner'
require 'paubox/models/message'
require 'paubox/models/message_content'
require 'paubox/models/message_delivery'
require 'paubox/models/message_headers'
require 'paubox/models/message_receipt_error_response'
require 'paubox/models/message_receipt_response'
require 'paubox/models/message_receipt_response_data'
require 'paubox/models/message_receipt_response_data_message'
require 'paubox/models/single_send_request'
require 'paubox/models/single_send_request_data'
require 'paubox/models/single_send_response'
require 'paubox/models/templated_message'
require 'paubox/models/templated_message_headers'
require 'paubox/models/templated_message_request'
require 'paubox/models/templated_message_request_data'

# APIs
require 'paubox/api/dynamic_templates_api'
require 'paubox/api/messages_api'

module Paubox
  class << self
    # Customize default settings for the SDK using block.
    #   Paubox.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
